# Automatically generated by make.py from ['rules.py']

_out/pty.o: pty.cpp
	mkdir -p _out
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Os -o _out/pty.o -c pty.cpp -MD -MP

-include _out/pty.d

_out/util.o: util.cpp
	mkdir -p _out
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Os -o _out/util.o -c util.cpp -MD -MP

-include _out/util.d

_out/protocol.o: protocol.cpp
	mkdir -p _out
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Os -o _out/protocol.o -c protocol.cpp -MD -MP

-include _out/protocol.d

_out/master.o: master.cpp
	mkdir -p _out
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Os -o _out/master.o -c master.cpp -MD -MP

-include _out/master.d

_out/slave.o: slave.cpp
	mkdir -p _out
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Os -o _out/slave.o -c slave.cpp -MD -MP

-include _out/slave.d

pty_proxy_master: _out/pty.o _out/util.o _out/protocol.o _out/master.o
	g++ -s -o pty_proxy_master _out/pty.o _out/util.o _out/protocol.o _out/master.o

pty_proxy_slave: _out/pty.o _out/util.o _out/protocol.o _out/slave.o
	g++ -s -o pty_proxy_slave _out/pty.o _out/util.o _out/protocol.o _out/slave.o

all: pty_proxy_master pty_proxy_slave
	true

